org: karstene
app: shortrlink
service: shortrlink-redirect

frameworkVersion: '2'
variablesResolutionMode: 20210326

plugins:
  - serverless-prune-plugin
  - serverless-python-requirements
  - serverless-domain-manager

package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'

custom:
  prune:
    automatic: true
    number: 5
  customDomain:
    domainName: '${self:custom.domainName.${sls:stage}}'
    certificateName: '*.shortr.link'
    createRoute53Record: true
    endpointType: 'regional'
    apiType: 'http'
  domainName:
    prod: 'shortr.link'
    dev: 'dev.shortr.link'

provider:
  name: aws
  lambdaHashingVersion: '20201221'
  profile: privateGmail
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  httpApi:
    cors: true
  tracing:
    apiGateway: true
    lambda: true
#  logs:
#    httpApi: true
  environment:
    DYNAMODB_TABLE: '${ssm:/shortrLink/${sls:stage}/dynamodb_table_name}'
    STAGE: '${sls:stage}'
    BASE_DOMAIN: '${self:custom.domainName.${sls:stage}}'
    REGION: '${self:provider.region}'
    EVENT_BUS_NAME: '${ssm:/shortrLink/${sls:stage}/eventbus_name}'
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:DescribeTable"
          Resource:
          - "${ssm:/shortrLink/${sls:stage}/dynamodb_table_arn}"
        - Effect: "Allow"
          Action:
            - "events:PutEvents"
          Resource:
            - 'arn:aws:events:${self:provider.region}:*:event-bus/${ssm:/shortrLink/${sls:stage}/eventbus_name}'

functions:
  redirect:
    handler: src/handlers/redirect.handler
    events:
      - httpApi:
          method: GET
          path: '/{linkId}'
