org: karstene
app: shortrlink
service: shortrlink-api

frameworkVersion: '2'
variablesResolutionMode: 20210326

plugins:
  - serverless-prune-plugin
  - serverless-python-requirements
  - serverless-domain-manager

package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'

custom:
  prune:
    automatic: true
    number: 5
  customDomain:
    domainName: '${self:custom.domainName.${sls:stage}}'
    certificateName: '*.shortrlink.com'
    createRoute53Record: true
    endpointType: 'regional'
    apiType: 'http'
  domainName:
    prod: api.shortrlink.com
    dev: api-dev.shortrlink.com

provider:
  name: aws
  lambdaHashingVersion: '20201221'
  profile: privateGmail
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  httpApi:
    cors: true
  tracing:
    apiGateway: true
    lambda: true
  logs:
    httpApi: true
  environment:
    DYNAMODB_TABLE: '${ssm:/shortrLink/${sls:stage}/dynamodb_table_name}'
    STAGE: '${sls:stage}'
    BASE_DOMAIN: 'shortr.link'
    REGION: '${self:provider.region}'
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:Query"
            - "dynamodb:GetItem"
            - "dynamodb:GetRecords"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DescribeTable"
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${ssm:/shortrLink/${sls:stage}/dynamodb_table_name}"

functions:
  createShortenedLink:
    handler: src/handlers/create_link.handler
    events:
      - httpApi:
          method: POST
          path: '/short-links'
  indexRedirectDynamoDb:
    handler: src/handlers/index_redirect_dynamodb.handler
    events:
      - eventBridge:
          eventBus: 'arn:aws:events:${self:provider.region}:*:event-bus/${ssm:/shortrLink/${sls:stage}/eventbus_name}'
          maximumRetryAttempts: 1
          pattern:
            source:
              - 'shortrLinks.lambda'
            detail-type:
              - 'shortrLink user redirect'
